# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pepfoot.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1406, 834)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(False)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setDocumentMode(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks|QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setAcceptDrops(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(5, 5, 10, 5)
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.ParameterBar = QtWidgets.QScrollArea(self.centralwidget)
        self.ParameterBar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ParameterBar.sizePolicy().hasHeightForWidth())
        self.ParameterBar.setSizePolicy(sizePolicy)
        self.ParameterBar.setMinimumSize(QtCore.QSize(300, 0))
        self.ParameterBar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ParameterBar.setAcceptDrops(True)
        self.ParameterBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ParameterBar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ParameterBar.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ParameterBar.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.ParameterBar.setWidgetResizable(True)
        self.ParameterBar.setObjectName("ParameterBar")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 300, 743))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 6)
        self.gridLayout_11.setSpacing(6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_11.addWidget(self.label_3, 10, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 14, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_3.addWidget(self.label_14)
        spacerItem = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.FileAdd = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FileAdd.sizePolicy().hasHeightForWidth())
        self.FileAdd.setSizePolicy(sizePolicy)
        self.FileAdd.setMinimumSize(QtCore.QSize(20, 20))
        self.FileAdd.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.FileAdd.setFont(font)
        self.FileAdd.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/img/list-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FileAdd.setIcon(icon)
        self.FileAdd.setIconSize(QtCore.QSize(16, 16))
        self.FileAdd.setCheckable(False)
        self.FileAdd.setDefault(False)
        self.FileAdd.setFlat(True)
        self.FileAdd.setObjectName("FileAdd")
        self.horizontalLayout_3.addWidget(self.FileAdd)
        self.FileConvert = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.FileConvert.setMinimumSize(QtCore.QSize(20, 20))
        self.FileConvert.setMaximumSize(QtCore.QSize(20, 20))
        self.FileConvert.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/img/Gnome-go-jump.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FileConvert.setIcon(icon1)
        self.FileConvert.setFlat(True)
        self.FileConvert.setObjectName("FileConvert")
        self.horizontalLayout_3.addWidget(self.FileConvert)
        self.FileRemove = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FileRemove.sizePolicy().hasHeightForWidth())
        self.FileRemove.setSizePolicy(sizePolicy)
        self.FileRemove.setMinimumSize(QtCore.QSize(20, 20))
        self.FileRemove.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.FileRemove.setFont(font)
        self.FileRemove.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/img/list-remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FileRemove.setIcon(icon2)
        self.FileRemove.setIconSize(QtCore.QSize(16, 16))
        self.FileRemove.setFlat(True)
        self.FileRemove.setObjectName("FileRemove")
        self.horizontalLayout_3.addWidget(self.FileRemove)
        self.gridLayout_11.addLayout(self.horizontalLayout_3, 7, 0, 1, 1)
        self.FixModList = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FixModList.sizePolicy().hasHeightForWidth())
        self.FixModList.setSizePolicy(sizePolicy)
        self.FixModList.setMinimumSize(QtCore.QSize(0, 60))
        self.FixModList.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.FixModList.setMouseTracking(True)
        self.FixModList.setMidLineWidth(0)
        self.FixModList.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.FixModList.setAlternatingRowColors(False)
        self.FixModList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.FixModList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.FixModList.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.FixModList.setModelColumn(0)
        self.FixModList.setSelectionRectVisible(False)
        self.FixModList.setObjectName("FixModList")
        self.gridLayout_11.addWidget(self.FixModList, 15, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_11.addItem(spacerItem1, 9, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_11.addItem(spacerItem2, 28, 0, 1, 1)
        self.DiffMod = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DiffMod.sizePolicy().hasHeightForWidth())
        self.DiffMod.setSizePolicy(sizePolicy)
        self.DiffMod.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.DiffMod.setObjectName("DiffMod")
        self.DiffMod.addItem("")
        self.gridLayout_11.addWidget(self.DiffMod, 16, 0, 1, 1)
        self.SeqInput = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SeqInput.sizePolicy().hasHeightForWidth())
        self.SeqInput.setSizePolicy(sizePolicy)
        self.SeqInput.setMinimumSize(QtCore.QSize(0, 50))
        self.SeqInput.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.SeqInput.setFont(font)
        self.SeqInput.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.SeqInput.setToolTip("")
        self.SeqInput.setToolTipDuration(-1)
        self.SeqInput.setPlainText("")
        self.SeqInput.setBackgroundVisible(False)
        self.SeqInput.setCenterOnScroll(False)
        self.SeqInput.setObjectName("SeqInput")
        self.gridLayout_11.addWidget(self.SeqInput, 11, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.MinLen = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.MinLen.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.MinLen.setFont(font)
        self.MinLen.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.MinLen.setSuffix("")
        self.MinLen.setMinimum(2)
        self.MinLen.setMaximum(10000)
        self.MinLen.setProperty("value", 5)
        self.MinLen.setObjectName("MinLen")
        self.gridLayout_10.addWidget(self.MinLen, 2, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_10.addWidget(self.label_19, 2, 4, 1, 1)
        self.MaxChg = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.MaxChg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.MaxChg.setFont(font)
        self.MaxChg.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.MaxChg.setMinimum(1)
        self.MaxChg.setMaximum(8)
        self.MaxChg.setProperty("value", 3)
        self.MaxChg.setObjectName("MaxChg")
        self.gridLayout_10.addWidget(self.MaxChg, 3, 5, 1, 1)
        self.MinChg = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.MinChg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.MinChg.setFont(font)
        self.MinChg.setFrame(True)
        self.MinChg.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.MinChg.setAccelerated(False)
        self.MinChg.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.MinChg.setProperty("showGroupSeparator", False)
        self.MinChg.setMinimum(1)
        self.MinChg.setMaximum(8)
        self.MinChg.setObjectName("MinChg")
        self.gridLayout_10.addWidget(self.MinChg, 3, 3, 1, 1)
        self.MaxLen = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.MaxLen.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.MaxLen.setFont(font)
        self.MaxLen.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.MaxLen.setSuffix("")
        self.MaxLen.setMinimum(1)
        self.MaxLen.setMaximum(99)
        self.MaxLen.setProperty("value", 20)
        self.MaxLen.setObjectName("MaxLen")
        self.gridLayout_10.addWidget(self.MaxLen, 2, 5, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_10.addWidget(self.label_20, 3, 4, 1, 1)
        self.MissCleave = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.MissCleave.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.MissCleave.setFont(font)
        self.MissCleave.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.MissCleave.setMaximum(3)
        self.MissCleave.setObjectName("MissCleave")
        self.gridLayout_10.addWidget(self.MissCleave, 5, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(3000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.gridLayout_10.addWidget(self.label, 5, 0, 1, 5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem3, 2, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setIndent(0)
        self.label_9.setObjectName("label_9")
        self.gridLayout_10.addWidget(self.label_9, 2, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setIndent(0)
        self.label_8.setObjectName("label_8")
        self.gridLayout_10.addWidget(self.label_8, 3, 0, 1, 2)
        self.Enzyme = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Enzyme.sizePolicy().hasHeightForWidth())
        self.Enzyme.setSizePolicy(sizePolicy)
        self.Enzyme.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Enzyme.setFont(font)
        self.Enzyme.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.Enzyme.setObjectName("Enzyme")
        self.Enzyme.addItem("")
        self.gridLayout_10.addWidget(self.Enzyme, 0, 0, 1, 6)
        self.gridLayout_11.addLayout(self.gridLayout_10, 19, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_11.addItem(spacerItem4, 20, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_11.addItem(spacerItem5, 17, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_11.addItem(spacerItem6, 12, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_11.addWidget(self.label_2, 18, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_11.addWidget(self.label_7, 21, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setIndent(0)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_5.addWidget(self.label_21)
        self.TolVal = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.TolVal.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.TolVal.setFont(font)
        self.TolVal.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.TolVal.setDecimals(0)
        self.TolVal.setMinimum(1.0)
        self.TolVal.setMaximum(500.0)
        self.TolVal.setSingleStep(1.0)
        self.TolVal.setProperty("value", 20.0)
        self.TolVal.setObjectName("TolVal")
        self.horizontalLayout_5.addWidget(self.TolVal)
        self.TolUnit = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TolUnit.sizePolicy().hasHeightForWidth())
        self.TolUnit.setSizePolicy(sizePolicy)
        self.TolUnit.setMinimumSize(QtCore.QSize(65, 0))
        self.TolUnit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.TolUnit.setFont(font)
        self.TolUnit.setDuplicatesEnabled(False)
        self.TolUnit.setFrame(False)
        self.TolUnit.setObjectName("TolUnit")
        self.TolUnit.addItem("")
        self.TolUnit.addItem("")
        self.horizontalLayout_5.addWidget(self.TolUnit)
        self.gridLayout_11.addLayout(self.horizontalLayout_5, 22, 0, 1, 1)
        self.FileList = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FileList.sizePolicy().hasHeightForWidth())
        self.FileList.setSizePolicy(sizePolicy)
        self.FileList.setMinimumSize(QtCore.QSize(0, 60))
        self.FileList.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.FileList.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.FileList.setAcceptDrops(False)
        self.FileList.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.FileList.setDragEnabled(True)
        self.FileList.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.FileList.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.FileList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.FileList.setWordWrap(True)
        self.FileList.setSelectionRectVisible(True)
        self.FileList.setObjectName("FileList")
        self.gridLayout_11.addWidget(self.FileList, 8, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.UpdateBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UpdateBtn.sizePolicy().hasHeightForWidth())
        self.UpdateBtn.setSizePolicy(sizePolicy)
        self.UpdateBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.UpdateBtn.setFont(font)
        self.UpdateBtn.setToolTip("")
        self.UpdateBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/img/Gnome-edit-find.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UpdateBtn.setIcon(icon3)
        self.UpdateBtn.setIconSize(QtCore.QSize(16, 16))
        self.UpdateBtn.setAutoDefault(False)
        self.UpdateBtn.setDefault(False)
        self.UpdateBtn.setFlat(False)
        self.UpdateBtn.setObjectName("UpdateBtn")
        self.horizontalLayout_2.addWidget(self.UpdateBtn)
        self.BatchBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.BatchBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BatchBtn.sizePolicy().hasHeightForWidth())
        self.BatchBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.BatchBtn.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/img/Gnome-system-run.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BatchBtn.setIcon(icon4)
        self.BatchBtn.setObjectName("BatchBtn")
        self.horizontalLayout_2.addWidget(self.BatchBtn)
        self.gridLayout_11.addLayout(self.horizontalLayout_2, 31, 0, 1, 1)
        self.ParameterBar.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.ParameterBar, 0, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.StatusBar = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StatusBar.sizePolicy().hasHeightForWidth())
        self.StatusBar.setSizePolicy(sizePolicy)
        self.StatusBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.StatusBar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.StatusBar.setText("")
        self.StatusBar.setObjectName("StatusBar")
        self.horizontalLayout_6.addWidget(self.StatusBar)
        self.ProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.ProgressBar.setEnabled(True)
        self.ProgressBar.setMinimumSize(QtCore.QSize(0, 15))
        self.ProgressBar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.ProgressBar.setMaximum(0)
        self.ProgressBar.setProperty("value", 0)
        self.ProgressBar.setTextVisible(True)
        self.ProgressBar.setInvertedAppearance(False)
        self.ProgressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.ProgressBar.setObjectName("ProgressBar")
        self.horizontalLayout_6.addWidget(self.ProgressBar)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 0, 1, 2)
        self.Tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.Tabs.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tabs.sizePolicy().hasHeightForWidth())
        self.Tabs.setSizePolicy(sizePolicy)
        self.Tabs.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Tabs.setFont(font)
        self.Tabs.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Tabs.setToolTip("")
        self.Tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.Tabs.setElideMode(QtCore.Qt.ElideNone)
        self.Tabs.setUsesScrollButtons(False)
        self.Tabs.setDocumentMode(False)
        self.Tabs.setTabsClosable(False)
        self.Tabs.setMovable(False)
        self.Tabs.setTabBarAutoHide(False)
        self.Tabs.setObjectName("Tabs")
        self.PeptideTab = QtWidgets.QWidget()
        self.PeptideTab.setEnabled(True)
        self.PeptideTab.setToolTip("")
        self.PeptideTab.setObjectName("PeptideTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.PeptideTab)
        self.gridLayout_3.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Ms1Charge = QtWidgets.QComboBox(self.PeptideTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ms1Charge.sizePolicy().hasHeightForWidth())
        self.Ms1Charge.setSizePolicy(sizePolicy)
        self.Ms1Charge.setMinimumSize(QtCore.QSize(0, 0))
        self.Ms1Charge.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Ms1Charge.setFont(font)
        self.Ms1Charge.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Ms1Charge.setObjectName("Ms1Charge")
        self.gridLayout_5.addWidget(self.Ms1Charge, 8, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.PeptideTab)
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 5, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.PeptideTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 8, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem8, 6, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.PeptideTab)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        font.setItalic(False)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 4, 0, 1, 1)
        self.CoverExp = QtWidgets.QLabel(self.PeptideTab)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        font.setItalic(False)
        self.CoverExp.setFont(font)
        self.CoverExp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.CoverExp.setObjectName("CoverExp")
        self.gridLayout_5.addWidget(self.CoverExp, 4, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem9, 15, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.PeptideTab)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        font.setItalic(False)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 3, 0, 1, 1)
        self.PepList = QtWidgets.QListWidget(self.PeptideTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PepList.sizePolicy().hasHeightForWidth())
        self.PepList.setSizePolicy(sizePolicy)
        self.PepList.setMinimumSize(QtCore.QSize(150, 0))
        self.PepList.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.PepList.setFont(font)
        self.PepList.setFocusPolicy(QtCore.Qt.NoFocus)
        self.PepList.setAutoFillBackground(False)
        self.PepList.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PepList.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.PepList.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.PepList.setTabKeyNavigation(False)
        self.PepList.setProperty("showDropIndicator", False)
        self.PepList.setIconSize(QtCore.QSize(12, 12))
        self.PepList.setTextElideMode(QtCore.Qt.ElideRight)
        self.PepList.setMovement(QtWidgets.QListView.Static)
        self.PepList.setFlow(QtWidgets.QListView.TopToBottom)
        self.PepList.setProperty("isWrapping", False)
        self.PepList.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.PepList.setViewMode(QtWidgets.QListView.ListMode)
        self.PepList.setUniformItemSizes(False)
        self.PepList.setSelectionRectVisible(True)
        self.PepList.setObjectName("PepList")
        self.gridLayout_5.addWidget(self.PepList, 2, 0, 1, 2)
        self.CoverPred = QtWidgets.QLabel(self.PeptideTab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.CoverPred.setFont(font)
        self.CoverPred.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.CoverPred.setObjectName("CoverPred")
        self.gridLayout_5.addWidget(self.CoverPred, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.PeptideTab)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 2, 2)
        self.Ms1Plot = QtWidgets.QWidget(self.PeptideTab)
        self.Ms1Plot.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ms1Plot.sizePolicy().hasHeightForWidth())
        self.Ms1Plot.setSizePolicy(sizePolicy)
        self.Ms1Plot.setMinimumSize(QtCore.QSize(500, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 249, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 249, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 249, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 249, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Ms1Plot.setPalette(palette)
        self.Ms1Plot.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.Ms1Plot.setMouseTracking(True)
        self.Ms1Plot.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Ms1Plot.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Ms1Plot.setAutoFillBackground(False)
        self.Ms1Plot.setObjectName("Ms1Plot")
        self.Ms1PlotVL = QtWidgets.QVBoxLayout(self.Ms1Plot)
        self.Ms1PlotVL.setObjectName("Ms1PlotVL")
        self.gridLayout_5.addWidget(self.Ms1Plot, 0, 2, 24, 1)
        self.PepIdLbl = QtWidgets.QLabel(self.PeptideTab)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.PepIdLbl.setFont(font)
        self.PepIdLbl.setText("")
        self.PepIdLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.PepIdLbl.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.PepIdLbl.setObjectName("PepIdLbl")
        self.gridLayout_5.addWidget(self.PepIdLbl, 7, 0, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.PeptideTab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 19, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem10, 23, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.PeptideTab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 17, 0, 1, 1)
        self.UnmodArea = QtWidgets.QLabel(self.PeptideTab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.UnmodArea.setFont(font)
        self.UnmodArea.setText("")
        self.UnmodArea.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.UnmodArea.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.UnmodArea.setObjectName("UnmodArea")
        self.gridLayout_5.addWidget(self.UnmodArea, 17, 1, 1, 1)
        self.FMod = QtWidgets.QLabel(self.PeptideTab)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.FMod.setFont(font)
        self.FMod.setText("")
        self.FMod.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.FMod.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.FMod.setObjectName("FMod")
        self.gridLayout_5.addWidget(self.FMod, 19, 1, 1, 1)
        self.ModArea = QtWidgets.QLabel(self.PeptideTab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ModArea.setFont(font)
        self.ModArea.setText("")
        self.ModArea.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ModArea.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.ModArea.setObjectName("ModArea")
        self.gridLayout_5.addWidget(self.ModArea, 18, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.PeptideTab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 18, 0, 1, 1)
        self.RemoveAssignment = QtWidgets.QPushButton(self.PeptideTab)
        self.RemoveAssignment.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/img/Gnome-window-close.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RemoveAssignment.setIcon(icon5)
        self.RemoveAssignment.setObjectName("RemoveAssignment")
        self.gridLayout_5.addWidget(self.RemoveAssignment, 21, 0, 1, 2)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_5.addItem(spacerItem11, 20, 0, 1, 1)
        self.PepModMzLbl = QtWidgets.QLabel(self.PeptideTab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.PepModMzLbl.setFont(font)
        self.PepModMzLbl.setText("")
        self.PepModMzLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PepModMzLbl.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.PepModMzLbl.setObjectName("PepModMzLbl")
        self.gridLayout_5.addWidget(self.PepModMzLbl, 11, 1, 1, 1)
        self.PepMzLbl = QtWidgets.QLabel(self.PeptideTab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.PepMzLbl.setFont(font)
        self.PepMzLbl.setText("")
        self.PepMzLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PepMzLbl.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.PepMzLbl.setObjectName("PepMzLbl")
        self.gridLayout_5.addWidget(self.PepMzLbl, 10, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem12, 9, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.PeptideTab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 10, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.PeptideTab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 11, 0, 1, 1)
        self.PepModMzErr = QtWidgets.QLabel(self.PeptideTab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.PepModMzErr.setFont(font)
        self.PepModMzErr.setText("")
        self.PepModMzErr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PepModMzErr.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.PepModMzErr.setObjectName("PepModMzErr")
        self.gridLayout_5.addWidget(self.PepModMzErr, 14, 1, 1, 1)
        self.PepMzErr = QtWidgets.QLabel(self.PeptideTab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.PepMzErr.setFont(font)
        self.PepMzErr.setText("")
        self.PepMzErr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PepMzErr.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.PepMzErr.setObjectName("PepMzErr")
        self.gridLayout_5.addWidget(self.PepMzErr, 13, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.PeptideTab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 13, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.PeptideTab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 14, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem13, 12, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.PeptideTab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_5.addWidget(self.line_2, 16, 0, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ZoomBtn = QtWidgets.QPushButton(self.PeptideTab)
        self.ZoomBtn.setCheckable(True)
        self.ZoomBtn.setChecked(True)
        self.ZoomBtn.setObjectName("ZoomBtn")
        self.horizontalLayout_4.addWidget(self.ZoomBtn)
        self.ExtractBtn = QtWidgets.QPushButton(self.PeptideTab)
        self.ExtractBtn.setCheckable(True)
        self.ExtractBtn.setObjectName("ExtractBtn")
        self.horizontalLayout_4.addWidget(self.ExtractBtn)
        self.IntegrateBtn = QtWidgets.QPushButton(self.PeptideTab)
        self.IntegrateBtn.setCheckable(True)
        self.IntegrateBtn.setObjectName("IntegrateBtn")
        self.horizontalLayout_4.addWidget(self.IntegrateBtn)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 22, 0, 1, 2)
        self.gridLayout_5.setColumnStretch(0, 1)
        self.gridLayout_3.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.Tabs.addTab(self.PeptideTab, "")
        self.AnalysisTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AnalysisTab.sizePolicy().hasHeightForWidth())
        self.AnalysisTab.setSizePolicy(sizePolicy)
        self.AnalysisTab.setObjectName("AnalysisTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.AnalysisTab)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_25 = QtWidgets.QLabel(self.AnalysisTab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_2.addWidget(self.label_25)
        self.ApoList = QtWidgets.QListWidget(self.AnalysisTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ApoList.sizePolicy().hasHeightForWidth())
        self.ApoList.setSizePolicy(sizePolicy)
        self.ApoList.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ApoList.setFont(font)
        self.ApoList.setAcceptDrops(True)
        self.ApoList.setDragEnabled(True)
        self.ApoList.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.ApoList.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.ApoList.setObjectName("ApoList")
        self.verticalLayout_2.addWidget(self.ApoList)
        self.label_26 = QtWidgets.QLabel(self.AnalysisTab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_2.addWidget(self.label_26)
        self.HoloList = QtWidgets.QListWidget(self.AnalysisTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HoloList.sizePolicy().hasHeightForWidth())
        self.HoloList.setSizePolicy(sizePolicy)
        self.HoloList.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.HoloList.setFont(font)
        self.HoloList.setAcceptDrops(False)
        self.HoloList.setDragEnabled(True)
        self.HoloList.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.HoloList.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.HoloList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.HoloList.setObjectName("HoloList")
        self.verticalLayout_2.addWidget(self.HoloList)
        spacerItem14 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem14)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_22 = QtWidgets.QLabel(self.AnalysisTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 1, 0, 1, 1)
        self.SigVal = QtWidgets.QDoubleSpinBox(self.AnalysisTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SigVal.sizePolicy().hasHeightForWidth())
        self.SigVal.setSizePolicy(sizePolicy)
        self.SigVal.setMaximum(1.0)
        self.SigVal.setSingleStep(0.05)
        self.SigVal.setProperty("value", 0.05)
        self.SigVal.setObjectName("SigVal")
        self.gridLayout_6.addWidget(self.SigVal, 1, 1, 1, 1)
        self.ThreshVal = QtWidgets.QDoubleSpinBox(self.AnalysisTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ThreshVal.sizePolicy().hasHeightForWidth())
        self.ThreshVal.setSizePolicy(sizePolicy)
        self.ThreshVal.setMaximum(1.0)
        self.ThreshVal.setSingleStep(0.05)
        self.ThreshVal.setProperty("value", 0.05)
        self.ThreshVal.setObjectName("ThreshVal")
        self.gridLayout_6.addWidget(self.ThreshVal, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.AnalysisTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 0, 0, 1, 1)
        self.DiffPlotChk = QtWidgets.QCheckBox(self.AnalysisTab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.DiffPlotChk.setFont(font)
        self.DiffPlotChk.setObjectName("DiffPlotChk")
        self.gridLayout_6.addWidget(self.DiffPlotChk, 3, 0, 1, 2)
        self.UnityChk = QtWidgets.QCheckBox(self.AnalysisTab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.UnityChk.setFont(font)
        self.UnityChk.setChecked(True)
        self.UnityChk.setObjectName("UnityChk")
        self.gridLayout_6.addWidget(self.UnityChk, 2, 0, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        self.AnalysisUpdateBtn = QtWidgets.QPushButton(self.AnalysisTab)
        self.AnalysisUpdateBtn.setObjectName("AnalysisUpdateBtn")
        self.verticalLayout_2.addWidget(self.AnalysisUpdateBtn)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem15)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.BarPlot = QtWidgets.QWidget(self.AnalysisTab)
        self.BarPlot.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.BarPlot.sizePolicy().hasHeightForWidth())
        self.BarPlot.setSizePolicy(sizePolicy)
        self.BarPlot.setMinimumSize(QtCore.QSize(0, 0))
        self.BarPlot.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 249, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 249, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 249, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 249, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.BarPlot.setPalette(palette)
        self.BarPlot.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.BarPlot.setMouseTracking(True)
        self.BarPlot.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.BarPlot.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.BarPlot.setAutoFillBackground(False)
        self.BarPlot.setObjectName("BarPlot")
        self.BarPlotVL = QtWidgets.QVBoxLayout(self.BarPlot)
        self.BarPlotVL.setObjectName("BarPlotVL")
        self.verticalLayout.addWidget(self.BarPlot)
        spacerItem16 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem16)
        self.PeptideLbl = QtWidgets.QLabel(self.AnalysisTab)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(14)
        self.PeptideLbl.setFont(font)
        self.PeptideLbl.setText("")
        self.PeptideLbl.setScaledContents(True)
        self.PeptideLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.PeptideLbl.setWordWrap(True)
        self.PeptideLbl.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.PeptideLbl.setObjectName("PeptideLbl")
        self.verticalLayout.addWidget(self.PeptideLbl)
        self.BarInfo = QtWidgets.QLabel(self.AnalysisTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.BarInfo.sizePolicy().hasHeightForWidth())
        self.BarInfo.setSizePolicy(sizePolicy)
        self.BarInfo.setMinimumSize(QtCore.QSize(0, 100))
        self.BarInfo.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.BarInfo.setFont(font)
        self.BarInfo.setText("")
        self.BarInfo.setScaledContents(True)
        self.BarInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.BarInfo.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.BarInfo.setObjectName("BarInfo")
        self.verticalLayout.addWidget(self.BarInfo)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 5)
        self.Tabs.addTab(self.AnalysisTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_3.addWidget(self.label_23)
        self.PdbName = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PdbName.sizePolicy().hasHeightForWidth())
        self.PdbName.setSizePolicy(sizePolicy)
        self.PdbName.setMinimumSize(QtCore.QSize(150, 0))
        self.PdbName.setMaximumSize(QtCore.QSize(250, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.PdbName.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.PdbName.setFont(font)
        self.PdbName.setAutoFillBackground(True)
        self.PdbName.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PdbName.setText("")
        self.PdbName.setScaledContents(True)
        self.PdbName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.PdbName.setWordWrap(True)
        self.PdbName.setObjectName("PdbName")
        self.verticalLayout_3.addWidget(self.PdbName)
        self.LoadPdb = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoadPdb.sizePolicy().hasHeightForWidth())
        self.LoadPdb.setSizePolicy(sizePolicy)
        self.LoadPdb.setObjectName("LoadPdb")
        self.verticalLayout_3.addWidget(self.LoadPdb)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem17)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem18)
        self.verticalLayout_3.setStretch(1, 1)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.NGLViewer = QtWebEngineWidgets.QWebEngineView(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.NGLViewer.sizePolicy().hasHeightForWidth())
        self.NGLViewer.setSizePolicy(sizePolicy)
        self.NGLViewer.setMinimumSize(QtCore.QSize(0, 0))
        self.NGLViewer.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.NGLViewer.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.NGLViewer.setAutoFillBackground(False)
        self.NGLViewer.setUrl(QtCore.QUrl("about:blank"))
        self.NGLViewer.setObjectName("NGLViewer")
        self.horizontalLayout_7.addWidget(self.NGLViewer)
        self.Tabs.addTab(self.tab, "")
        self.gridLayout.addWidget(self.Tabs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1406, 20))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menu_Edit = QtWidgets.QMenu(self.menubar)
        self.menu_Edit.setAcceptDrops(False)
        self.menu_Edit.setObjectName("menu_Edit")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(24, 24))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/img/Gnome-help-faq.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon6)
        self.actionAbout.setIconVisibleInMenu(True)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOpenProject = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/img/Gnome-document-open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenProject.setIcon(icon7)
        self.actionOpenProject.setObjectName("actionOpenProject")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setIcon(icon5)
        self.actionQuit.setMenuRole(QtWidgets.QAction.QuitRole)
        self.actionQuit.setIconVisibleInMenu(True)
        self.actionQuit.setObjectName("actionQuit")
        self.actionNewProject = QtWidgets.QAction(MainWindow)
        self.actionNewProject.setCheckable(False)
        self.actionNewProject.setChecked(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/img/Gnome-document-new.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewProject.setIcon(icon8)
        self.actionNewProject.setAutoRepeat(True)
        self.actionNewProject.setVisible(True)
        self.actionNewProject.setIconVisibleInMenu(True)
        self.actionNewProject.setObjectName("actionNewProject")
        self.actionSaveProject = QtWidgets.QAction(MainWindow)
        self.actionSaveProject.setCheckable(False)
        self.actionSaveProject.setEnabled(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/img/Gnome-document-save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveProject.setIcon(icon9)
        self.actionSaveProject.setObjectName("actionSaveProject")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/img/Gnome-help-contents.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDocumentation.setIcon(icon10)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionEditMods = QtWidgets.QAction(MainWindow)
        self.actionEditMods.setIconVisibleInMenu(False)
        self.actionEditMods.setObjectName("actionEditMods")
        self.actionEditCleavages = QtWidgets.QAction(MainWindow)
        self.actionEditCleavages.setIconVisibleInMenu(False)
        self.actionEditCleavages.setObjectName("actionEditCleavages")
        self.actionDisplay_Parameters = QtWidgets.QAction(MainWindow)
        self.actionDisplay_Parameters.setIconVisibleInMenu(False)
        self.actionDisplay_Parameters.setObjectName("actionDisplay_Parameters")
        self.actionBatch = QtWidgets.QAction(MainWindow)
        self.actionBatch.setEnabled(True)
        self.actionBatch.setIcon(icon4)
        self.actionBatch.setVisible(True)
        self.actionBatch.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionBatch.setIconVisibleInMenu(True)
        self.actionBatch.setObjectName("actionBatch")
        self.actionCite = QtWidgets.QAction(MainWindow)
        self.actionCite.setObjectName("actionCite")
        self.actionLicense = QtWidgets.QAction(MainWindow)
        self.actionLicense.setObjectName("actionLicense")
        self.actionOpen_Recent = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/img/Gnome-document-open-recent.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Recent.setIcon(icon11)
        self.actionOpen_Recent.setObjectName("actionOpen_Recent")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionAcknowledgements = QtWidgets.QAction(MainWindow)
        self.actionAcknowledgements.setObjectName("actionAcknowledgements")
        self.actionExportCSV = QtWidgets.QAction(MainWindow)
        self.actionExportCSV.setCheckable(False)
        self.actionExportCSV.setEnabled(False)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/img/accessories-text-editor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExportCSV.setIcon(icon12)
        self.actionExportCSV.setVisible(True)
        self.actionExportCSV.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionExportCSV.setObjectName("actionExportCSV")
        self.actionHideParam = QtWidgets.QAction(MainWindow)
        self.actionHideParam.setCheckable(True)
        self.actionHideParam.setChecked(False)
        self.actionHideParam.setIconVisibleInMenu(False)
        self.actionHideParam.setObjectName("actionHideParam")
        self.actionInMemory = QtWidgets.QAction(MainWindow)
        self.actionInMemory.setCheckable(True)
        self.actionInMemory.setChecked(True)
        self.actionInMemory.setObjectName("actionInMemory")
        self.actionNew_from_Template = QtWidgets.QAction(MainWindow)
        self.actionNew_from_Template.setObjectName("actionNew_from_Template")
        self.menuFile.addAction(self.actionNewProject)
        self.menuFile.addAction(self.actionNew_from_Template)
        self.menuFile.addAction(self.actionOpenProject)
        self.menuFile.addAction(self.actionOpen_Recent)
        self.menuFile.addAction(self.actionSaveProject)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionHideParam)
        self.menuFile.addAction(self.actionInMemory)
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionCite)
        self.menuHelp.addAction(self.actionLicense)
        self.menuHelp.addAction(self.actionAcknowledgements)
        self.menu_Edit.addAction(self.actionEditMods)
        self.menu_Edit.addAction(self.actionEditCleavages)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNewProject)
        self.toolBar.addAction(self.actionOpenProject)
        self.toolBar.addAction(self.actionSaveProject)
        self.toolBar.addAction(self.actionBatch)
        self.toolBar.addAction(self.actionExportCSV)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionEditMods)
        self.toolBar.addAction(self.actionEditCleavages)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHideParam)

        self.retranslateUi(MainWindow)
        self.Tabs.setCurrentIndex(0)
        self.actionHideParam.toggled['bool'].connect(self.ParameterBar.setHidden)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pepFoot"))
        self.label_3.setText(_translate("MainWindow", "Sequence"))
        self.label_6.setToolTip(_translate("MainWindow", "Modifications applied to all possible residues, multiple per peptide"))
        self.label_6.setText(_translate("MainWindow", "Modifications"))
        self.label_14.setText(_translate("MainWindow", "Data Files"))
        self.FileAdd.setToolTip(_translate("MainWindow", "Add .mz5 Files"))
        self.FileConvert.setToolTip(_translate("MainWindow", "Convert MS Files"))
        self.FileRemove.setToolTip(_translate("MainWindow", "Remove Files"))
        self.FixModList.setSortingEnabled(False)
        self.DiffMod.setItemText(0, _translate("MainWindow", "None"))
        self.SeqInput.setWhatsThis(_translate("MainWindow", "Enter the FASTA sequence for the protein being investigated."))
        self.SeqInput.setPlaceholderText(_translate("MainWindow", "Paste/drag and drop sequence here"))
        self.label_19.setText(_translate("MainWindow", " - "))
        self.label_20.setText(_translate("MainWindow", " - "))
        self.label.setToolTip(_translate("MainWindow", "Number of missed cleavages to consider"))
        self.label.setText(_translate("MainWindow", "# Missed Cleavages"))
        self.label_9.setToolTip(_translate("MainWindow", "Mass range used by the instrument"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p>Peptide Length</p></body></html>"))
        self.label_8.setToolTip(_translate("MainWindow", "Range of peptide charge states to consider"))
        self.label_8.setText(_translate("MainWindow", "Peptide Charge"))
        self.Enzyme.setItemText(0, _translate("MainWindow", "None"))
        self.label_2.setText(_translate("MainWindow", "Digestion"))
        self.label_7.setText(_translate("MainWindow", "MS Parameters"))
        self.label_21.setText(_translate("MainWindow", "Tolerance"))
        self.TolUnit.setItemText(0, _translate("MainWindow", "mmu"))
        self.TolUnit.setItemText(1, _translate("MainWindow", "ppm"))
        self.FileList.setSortingEnabled(False)
        self.UpdateBtn.setText(_translate("MainWindow", "Explore"))
        self.BatchBtn.setToolTip(_translate("MainWindow", "Batch Process all Data Files"))
        self.BatchBtn.setText(_translate("MainWindow", "Batch"))
        self.ProgressBar.setFormat(_translate("MainWindow", "%v/%m"))
        self.label_5.setText(_translate("MainWindow", "Charge State"))
        self.label_17.setToolTip(_translate("MainWindow", "Coverage of protein by peptides"))
        self.label_17.setText(_translate("MainWindow", "Experimental"))
        self.CoverExp.setText(_translate("MainWindow", "N/A"))
        self.label_16.setToolTip(_translate("MainWindow", "Coverage of protein by peptides"))
        self.label_16.setText(_translate("MainWindow", "Predicted"))
        self.PepList.setToolTip(_translate("MainWindow", "<html><head/><body><p>List of peptides</p></body></html>"))
        self.CoverPred.setText(_translate("MainWindow", "N/A"))
        self.label_4.setText(_translate("MainWindow", "Peptides"))
        self.label_15.setText(_translate("MainWindow", "Modification"))
        self.label_10.setText(_translate("MainWindow", "Unmodified Area"))
        self.label_13.setText(_translate("MainWindow", "Modified Area"))
        self.RemoveAssignment.setText(_translate("MainWindow", "Remove Assignment"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p>Unmodified <span style=\" font-style:italic;\">m/z</span></p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p>Modified <span style=\" font-style:italic;\">m/z</span></p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p>Unmodified <span style=\" font-style:italic;\">m/z</span> error</p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p>Modified <span style=\" font-style:italic;\">m/z</span> error</p></body></html>"))
        self.ZoomBtn.setText(_translate("MainWindow", "Zoom"))
        self.ExtractBtn.setText(_translate("MainWindow", "Extract"))
        self.IntegrateBtn.setText(_translate("MainWindow", "Integrate"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.PeptideTab), _translate("MainWindow", "Peptide Level"))
        self.label_25.setText(_translate("MainWindow", "Apo"))
        self.label_26.setText(_translate("MainWindow", "Holo"))
        self.label_22.setText(_translate("MainWindow", "Significance"))
        self.label_18.setText(_translate("MainWindow", "Threshold"))
        self.DiffPlotChk.setText(_translate("MainWindow", "Difference Plot"))
        self.UnityChk.setText(_translate("MainWindow", "Unity"))
        self.AnalysisUpdateBtn.setText(_translate("MainWindow", "Update"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.AnalysisTab), _translate("MainWindow", "Analysis"))
        self.label_23.setText(_translate("MainWindow", "PDB"))
        self.LoadPdb.setText(_translate("MainWindow", "Load PDB"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p>Controls</p><p><span style=\" font-size:9pt;\">C: </span><span style=\" font-size:9pt; font-style:italic;\">Cartoon Toggle</span></p><p><span style=\" font-size:9pt;\">H: </span><span style=\" font-size:9pt; font-style:italic;\">Hetero Object Toggle</span></p><p><span style=\" font-size:9pt; font-style:italic;\">R: Recenter view</span></p><p><span style=\" font-size:9pt;\">Left Move: </span><span style=\" font-size:9pt; font-style:italic;\">Rotate around center</span></p><p><span style=\" font-size:9pt;\">Right Move:</span><span style=\" font-size:9pt; font-style:italic;\"> Move in plane</span></p><p><span style=\" font-size:9pt;\">Shift + Left or Middle: </span><span style=\" font-size:9pt; font-style:italic;\">Zoom</span></p><p><span style=\" font-size:9pt;\">Shift + Middle: </span><span style=\" font-size:9pt; font-style:italic;\">Clip Plane </span></p></body></html>"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab), _translate("MainWindow", "NGL Viewer"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionAbout.setText(_translate("MainWindow", "&About PepFoot"))
        self.actionOpenProject.setText(_translate("MainWindow", "&Open Project"))
        self.actionOpenProject.setIconText(_translate("MainWindow", "Open"))
        self.actionOpenProject.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit PepFoot"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionNewProject.setText(_translate("MainWindow", "&New Project"))
        self.actionNewProject.setIconText(_translate("MainWindow", "New"))
        self.actionNewProject.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSaveProject.setText(_translate("MainWindow", "&Save Project"))
        self.actionSaveProject.setIconText(_translate("MainWindow", "Save"))
        self.actionSaveProject.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionDocumentation.setText(_translate("MainWindow", "&Documentation"))
        self.actionEditMods.setText(_translate("MainWindow", "&Modifications"))
        self.actionEditCleavages.setText(_translate("MainWindow", "&Enzymes"))
        self.actionDisplay_Parameters.setText(_translate("MainWindow", "&Display Parameters"))
        self.actionBatch.setText(_translate("MainWindow", "Batch Process"))
        self.actionBatch.setIconText(_translate("MainWindow", "Batch"))
        self.actionBatch.setToolTip(_translate("MainWindow", "Batch Process All Files in Current Project"))
        self.actionCite.setText(_translate("MainWindow", "How to &Cite"))
        self.actionLicense.setText(_translate("MainWindow", "&License"))
        self.actionOpen_Recent.setText(_translate("MainWindow", "Open &Recent"))
        self.actionOpen_Recent.setToolTip(_translate("MainWindow", "Open Recent Projects"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionAcknowledgements.setText(_translate("MainWindow", "Acknowledgements"))
        self.actionExportCSV.setText(_translate("MainWindow", "Export to CSV"))
        self.actionExportCSV.setIconText(_translate("MainWindow", "Export"))
        self.actionExportCSV.setToolTip(_translate("MainWindow", "Export current data to CSV"))
        self.actionExportCSV.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionHideParam.setText(_translate("MainWindow", "Hide Parameter Bar"))
        self.actionHideParam.setIconText(_translate("MainWindow", "Hide"))
        self.actionHideParam.setToolTip(_translate("MainWindow", "Hide Parameter Bar"))
        self.actionHideParam.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.actionInMemory.setText(_translate("MainWindow", "In Memory"))
        self.actionNew_from_Template.setText(_translate("MainWindow", "New from Template"))

from PyQt5 import QtWebEngineWidgets
from gui import icons_rc
