# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferences.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 500)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.Tabs = QtWidgets.QTabWidget(Dialog)
        self.Tabs.setEnabled(True)
        self.Tabs.setObjectName("Tabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.ModTable = QtWidgets.QTableWidget(self.tab)
        self.ModTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ModTable.setProperty("showDropIndicator", False)
        self.ModTable.setAlternatingRowColors(True)
        self.ModTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.ModTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ModTable.setShowGrid(False)
        self.ModTable.setGridStyle(QtCore.Qt.NoPen)
        self.ModTable.setObjectName("ModTable")
        self.ModTable.setColumnCount(6)
        self.ModTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.ModTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ModTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ModTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.ModTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.ModTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ModTable.setHorizontalHeaderItem(5, item)
        self.ModTable.horizontalHeader().setDefaultSectionSize(80)
        self.ModTable.horizontalHeader().setHighlightSections(False)
        self.ModTable.horizontalHeader().setSortIndicatorShown(False)
        self.ModTable.horizontalHeader().setStretchLastSection(True)
        self.ModTable.verticalHeader().setVisible(False)
        self.ModTable.verticalHeader().setDefaultSectionSize(20)
        self.ModTable.verticalHeader().setHighlightSections(False)
        self.verticalLayout.addWidget(self.ModTable)
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 4, 7, 1, 1)
        self.ModID = QtWidgets.QLineEdit(self.widget)
        self.ModID.setMinimumSize(QtCore.QSize(20, 0))
        self.ModID.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ModID.setInputMask("")
        self.ModID.setText("")
        self.ModID.setMaxLength(10)
        self.ModID.setFrame(True)
        self.ModID.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ModID.setClearButtonEnabled(True)
        self.ModID.setObjectName("ModID")
        self.gridLayout_3.addWidget(self.ModID, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 4, 12, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 4, 1, 1)
        self.ModAdd = QtWidgets.QPushButton(self.widget)
        self.ModAdd.setEnabled(False)
        self.ModAdd.setMaximumSize(QtCore.QSize(20, 20))
        self.ModAdd.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/img/list-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ModAdd.setIcon(icon)
        self.ModAdd.setFlat(True)
        self.ModAdd.setObjectName("ModAdd")
        self.gridLayout_3.addWidget(self.ModAdd, 1, 10, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 4, 0, 1, 1)
        self.ModRemove = QtWidgets.QPushButton(self.widget)
        self.ModRemove.setEnabled(False)
        self.ModRemove.setMaximumSize(QtCore.QSize(20, 20))
        self.ModRemove.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/img/list-remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ModRemove.setIcon(icon1)
        self.ModRemove.setFlat(True)
        self.ModRemove.setObjectName("ModRemove")
        self.gridLayout_3.addWidget(self.ModRemove, 4, 10, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 9, 1, 1)
        self.ModGain = QtWidgets.QLineEdit(self.widget)
        self.ModGain.setMinimumSize(QtCore.QSize(80, 0))
        self.ModGain.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ModGain.setClearButtonEnabled(True)
        self.ModGain.setObjectName("ModGain")
        self.gridLayout_3.addWidget(self.ModGain, 4, 8, 1, 1)
        self.ModResi = QtWidgets.QLineEdit(self.widget)
        self.ModResi.setMinimumSize(QtCore.QSize(80, 0))
        self.ModResi.setMaximumSize(QtCore.QSize(300, 16777215))
        self.ModResi.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ModResi.setReadOnly(False)
        self.ModResi.setClearButtonEnabled(True)
        self.ModResi.setObjectName("ModResi")
        self.gridLayout_3.addWidget(self.ModResi, 1, 5, 1, 1)
        self.ModDesc = QtWidgets.QLineEdit(self.widget)
        self.ModDesc.setMaximumSize(QtCore.QSize(16505, 16777215))
        self.ModDesc.setClearButtonEnabled(True)
        self.ModDesc.setObjectName("ModDesc")
        self.gridLayout_3.addWidget(self.ModDesc, 4, 2, 1, 4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 7, 1, 1)
        self.ModLoss = QtWidgets.QLineEdit(self.widget)
        self.ModLoss.setMinimumSize(QtCore.QSize(80, 0))
        self.ModLoss.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ModLoss.setClearButtonEnabled(True)
        self.ModLoss.setObjectName("ModLoss")
        self.gridLayout_3.addWidget(self.ModLoss, 1, 8, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 1, 6, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.Tabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.EnzymeTable = QtWidgets.QTableWidget(self.tab_2)
        self.EnzymeTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.EnzymeTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.EnzymeTable.setAlternatingRowColors(True)
        self.EnzymeTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.EnzymeTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.EnzymeTable.setShowGrid(False)
        self.EnzymeTable.setGridStyle(QtCore.Qt.DotLine)
        self.EnzymeTable.setCornerButtonEnabled(True)
        self.EnzymeTable.setObjectName("EnzymeTable")
        self.EnzymeTable.setColumnCount(3)
        self.EnzymeTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.EnzymeTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.EnzymeTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.EnzymeTable.setHorizontalHeaderItem(2, item)
        self.EnzymeTable.horizontalHeader().setCascadingSectionResizes(False)
        self.EnzymeTable.horizontalHeader().setDefaultSectionSize(185)
        self.EnzymeTable.horizontalHeader().setHighlightSections(False)
        self.EnzymeTable.horizontalHeader().setSortIndicatorShown(False)
        self.EnzymeTable.horizontalHeader().setStretchLastSection(True)
        self.EnzymeTable.verticalHeader().setVisible(False)
        self.EnzymeTable.verticalHeader().setDefaultSectionSize(20)
        self.EnzymeTable.verticalHeader().setHighlightSections(False)
        self.verticalLayout_2.addWidget(self.EnzymeTable)
        self.widget_2 = QtWidgets.QWidget(self.tab_2)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.EnzymeCterm = QtWidgets.QLineEdit(self.widget_2)
        self.EnzymeCterm.setClearButtonEnabled(True)
        self.EnzymeCterm.setObjectName("EnzymeCterm")
        self.gridLayout_2.addWidget(self.EnzymeCterm, 0, 5, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        self.label_10.setMinimumSize(QtCore.QSize(0, 15))
        self.label_10.setMaximumSize(QtCore.QSize(15, 15))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/icons/img/Gnome-edit-cut.svg"))
        self.label_10.setScaledContents(True)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 4, 1, 1)
        self.EnzymeName = QtWidgets.QLineEdit(self.widget_2)
        self.EnzymeName.setClearButtonEnabled(True)
        self.EnzymeName.setObjectName("EnzymeName")
        self.gridLayout_2.addWidget(self.EnzymeName, 0, 1, 1, 1)
        self.EnzymeNterm = QtWidgets.QLineEdit(self.widget_2)
        self.EnzymeNterm.setClearButtonEnabled(True)
        self.EnzymeNterm.setObjectName("EnzymeNterm")
        self.gridLayout_2.addWidget(self.EnzymeNterm, 0, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 2, 1, 1)
        self.EnzymeAdd = QtWidgets.QPushButton(self.widget_2)
        self.EnzymeAdd.setEnabled(False)
        self.EnzymeAdd.setMaximumSize(QtCore.QSize(20, 20))
        self.EnzymeAdd.setText("")
        self.EnzymeAdd.setIcon(icon)
        self.EnzymeAdd.setFlat(True)
        self.EnzymeAdd.setObjectName("EnzymeAdd")
        self.gridLayout_2.addWidget(self.EnzymeAdd, 0, 6, 1, 1)
        self.EnzymeRemove = QtWidgets.QPushButton(self.widget_2)
        self.EnzymeRemove.setEnabled(False)
        self.EnzymeRemove.setMaximumSize(QtCore.QSize(20, 20))
        self.EnzymeRemove.setText("")
        self.EnzymeRemove.setIcon(icon1)
        self.EnzymeRemove.setFlat(True)
        self.EnzymeRemove.setObjectName("EnzymeRemove")
        self.gridLayout_2.addWidget(self.EnzymeRemove, 0, 7, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.Tabs.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.Tabs, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.Tabs.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.Tabs, self.ModID)
        Dialog.setTabOrder(self.ModID, self.ModDesc)
        Dialog.setTabOrder(self.ModDesc, self.ModResi)
        Dialog.setTabOrder(self.ModResi, self.ModLoss)
        Dialog.setTabOrder(self.ModLoss, self.ModGain)
        Dialog.setTabOrder(self.ModGain, self.ModAdd)
        Dialog.setTabOrder(self.ModAdd, self.ModRemove)
        Dialog.setTabOrder(self.ModRemove, self.EnzymeTable)
        Dialog.setTabOrder(self.EnzymeTable, self.ModTable)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p>Modifications are defined by a unique ID, amino acid specificity and the formulae for loss and gain; the monoisotopic mass shift is then calculated.<br/><span style=\" font-size:8pt; font-style:italic;\">(Isotopes may be indicated with square brackets, e.g. H[2] for deuterium</span><span style=\" font-style:italic;\">)</span></p></body></html>"))
        self.ModTable.setSortingEnabled(True)
        item = self.ModTable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ID"))
        item = self.ModTable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Loss"))
        item = self.ModTable.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Gain"))
        item = self.ModTable.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Mass Shift"))
        item = self.ModTable.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Residues"))
        item = self.ModTable.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Description"))
        self.label_8.setText(_translate("Dialog", "Gain"))
        self.label_2.setText(_translate("Dialog", "ID"))
        self.label_4.setText(_translate("Dialog", "Description"))
        self.label_3.setText(_translate("Dialog", "Residues"))
        self.label_5.setText(_translate("Dialog", "Loss"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab), _translate("Dialog", "Modifications"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p>Place residues for a given position within square brackets <span style=\" font-weight:600;\">[]</span>, for anti-specific residues indicate with a <span style=\" font-weight:600;\">^</span> and for <span style=\" font-style:italic;\">Xaa</span> positions indicate with <span style=\" font-weight:600;\">[A-Z]</span>.</p></body></html>"))
        item = self.EnzymeTable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Name"))
        item = self.EnzymeTable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "N-Terminal"))
        item = self.EnzymeTable.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "C-Terminal"))
        self.EnzymeCterm.setPlaceholderText(_translate("Dialog", "C-terminal to cut"))
        self.label_7.setText(_translate("Dialog", "Name"))
        self.EnzymeName.setPlaceholderText(_translate("Dialog", "Name of enzyme"))
        self.EnzymeNterm.setPlaceholderText(_translate("Dialog", "N-terminal to cut"))
        self.label_9.setText(_translate("Dialog", "Sequence"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_2), _translate("Dialog", "Enzymes"))

from gui import icons_rc
